### ISSUE TITLE
Implementation attribute check failing if exception raised within property

### ISSUE THREAD

**Issue by skinny121** [seequent/pure_interface#23]
The following code snippet produces the error: 
TypeError: AnimalAttribute.__init__ does not create required attribute "height"
```python
class IAnimalAttribute(PureInterface):
    height = None


class AnimalAttribute(object, IAnimalAttribute):
    @property
    def height(self):
        raise Exception("Bang")


animal = AnimalAttribute()
```

This is caused by python 2 hasattr behaviour meaning if any exception in a property is raised hasattr returns false. Also confusingly the following works, contrary to the README which states "The use of class attribute or @property to define a class attribute are interchangeable":
```python 
class IAnimal(PureInterface):
    @abstractproperty
    def height(self):
        pass


class Animal(object, IAnimal):
    @property
    def height(self):
        raise Exception("Bang")


animal = Animal()
```

**Comment by tim-mitchell** [comment]
fixed in 3.2
