### ISSUE TITLE
Extend property check to look at superclasses

### ISSUE THREAD

**Issue by rockg** [seequent/pure_interface#58]
Attached is a patch file that adds superclass attributes when determining if a property from the interface is implemented.

Also, running a profile on this change it became evident that `issubclass(base, PureInterface)` is particularly slow. This reverses the order of arguments so that the slow statement is only evaluated if the `is_development` flag is True.

[namespace_check.txt](https://github.com/seequent/pure_interface/files/3458772/namespace_check.txt)

**Comment by tim-mitchell** [comment]
Fixed in 3.3.2 and 3.5.2
