### ISSUE TITLE
Adding interface to a subclass of a subclass causes properties to be called

### ISSUE THREAD

**Issue by skinny121** [seequent/pure_interface#65]
The following causes the `next` property to be executed when the instance is created, leading to a tb due to infinite recursion. 

```python

import pure_interface


class IA(pure_interface.PureInterface):
    next = None


class IOther(IA):
    pass


class A(object, IA):
    @property
    def next(self):
        print("next")
        return self.__class__()


class B(A):
    pass


class C(B, IOther):
    pass


C()
```
The property isn't every executed if `C` class definition is changed to either `class C(A, IOther):` or `class C(B):`.

**Comment by tim-mitchell** [comment]
Turns out this is because hasattr can attempt to fetch the attribute.
