### ISSUE TITLE
Async methods raise "not empty" error

### ISSUE THREAD

**Issue by ThomasMatern** [seequent/pure_interface#87]
Steps to reproduce: add an async interface method, e.g.
```
async def i_am_empty(self):
    pass
```
This raises:
```
pure_interface.InterfaceError: Function "i_am_empty" is not empty.
Did you forget to inherit from object to make the class concrete?
```
`_is_empty_function` currently allows a `return None` and an optional `raise NotImplementedError`. Async methods however have an additional `GEN_START` instruction, which is not handled.

**Comment by tim-mitchell** [comment]
Fixed in 6.0.1
