### ISSUE TITLE
is_empty fails when running optimized Python

### ISSUE THREAD

**Issue by ThomasMatern** [seequent/pure_interface#88]
Steps to reproduce:
- use Python 3.10.6
- run it with "-OO"
- import an interface that has a function with just a "pass"

_is_empty_function fails this function because the compiled code returns:
NOP, LOAD_CONST, RETURN_VALUE

Fix: also drop NOP, just like GEN_START and RESUME

**Comment by tim-mitchell** [comment]
Fixed in 6.0.2
